### PR TITLE
Upgrade Go SDK to 1.28.1

### PR DESCRIPTION
**Pull request by bergundy**

### CODE REVIEW

**Comment by Quinn-With-Two-Ns** [comment]
Shouldn't you upgrade the SDK here as well https://github.com/temporalio/features/blob/main/go.mod?

**Comment by bergundy** [comment]
> Shouldn't you upgrade the SDK here as well https://github.com/temporalio/features/blob/main/go.mod?

Done.

**Comment by Quinn-With-Two-Ns** [comment]
I always update these as well, not  sure if it is strictly necessary? 

https://github.com/temporalio/features/blob/main/harness/go/go.mod

https://github.com/temporalio/features/blob/main/features/go.mod

**Review by Quinn-With-Two-Ns — APPROVED** [review]

**Comment by bergundy** [comment]
> I always update these as well, not sure if it is strictly necessary?
> 
> https://github.com/temporalio/features/blob/main/harness/go/go.mod
> 
> https://github.com/temporalio/features/blob/main/features/go.mod

Thanks, done.

**Pull request merged**
