### PR TITLE
Update sdk-go dependency to v1.21.0

### PR DESCRIPTION
**Pull request by mmcshane**
## What was changed

Update sdk-go dependency to v1.21.0

## Why?

Good dependency hygiene

## Checklist

1. Closes 

2. How was this tested:

Ran all Go feature tests

3. Any docs updates needed?

No

### CODE REVIEW

**Comment by Quinn-With-Two-Ns** [comment]
I think you need to update the `go-ver` in the docker image task

**Comment by mmcshane** [comment]
@Quinn-With-Two-Ns it looks like that's for the Go version not the SDK version

**Comment by mmcshane** [comment]
@Quinn-With-Two-Ns Weird that it was on 1.19? I thought it was for the Go language version. Anyway, updated to 1.21

**Review by Quinn-With-Two-Ns — APPROVED** [review]

**Comment by Quinn-With-Two-Ns** [comment]
@mmcshane Since I did the 1.20 release you can blame me

**Pull request merged**
